Added code to display Total Portfolio Value
Mephiles/torntools_extension pull request #307
Opened 2020-12-28 04:35 UTC by Sashank999

2020-12-28 08:39 UTC, DeKleineKobini commented on torntools/scripts/content/stockexchange/ttStockexchange.js
> +totalPortfolio.style.fontSize = "18px;
Honestly, I don't like it being bigger than literally anything else in TT. I would just remove this.

2020-12-28 08:44 UTC, DeKleineKobini requested changes
The entire location of this code is wrong.
It's in the right file, but you can't just put it at the bottom and assume it will work.

2020-12-28 10:24 UTC, Mephiles commented
Also, could you move the value into the black "Your portfolio" heading as this will just remove clutter and unnecessary containers. It could look like this: 'Your portfolio ($1,000,000)'

2020-12-29 15:07 UTC, Sashank999 commented
Now I have changed the code. Thanks to Mephiles for the suggestions in removing some code. Now it looks like this :
![Stock Exchange _ TORN - Google Chrome 29-Dec-20 8_33_15 PM](https://user-images.githubusercontent.com/76554862/103293302-9cc72e80-4a15-11eb-978e-2b84856792ce.png)

2020-12-30 14:43 UTC, Sashank999 commented
Added changes as per the TT Standards.

2020-12-30 14:47 UTC, merged