B&I Warning Added
Mephiles/torntools_extension pull request #316
Opened 2021-01-09 11:32 UTC by Sashank999

#306 is added.

2021-01-09 12:12 UTC, DeKleineKobini reviewed
I don't think you ran the prettier formatter, as I think it adds spaces inside the objects (`{ childList: true }`)

2021-01-09 13:09 UTC, DeKleineKobini requested changes
We've updated our CONTRIBUTING.md, it's no longer optional to run Prettier.

2021-01-09 13:09 UTC, DeKleineKobini commented on torntools/scripts/content/forums/ttForums.js
> +		ttBugWarning.innerHTML = "<br>Please try disabling TornTools to make sure if the issue persists.&nbsp;Contact <a href='https://www.torn.com/profiles.php?XID=2087524' style='color:#f2f2f2'>Mephiles
HTML can be added as option inside `doc.new` as html.

2021-01-09 13:09 UTC, DeKleineKobini commented on torntools/scripts/content/forums/ttForums.js
> +		ttBugWarning.style.cssText = "background: repeating-linear-gradient(90deg,#627e0d,#627e0d 2px,#6e8820 0,#6e8820 4px); font-size: 16px; height: 59px; line-height: 16px; color: #ffffff; font-weight:
CSS like this preferably is applied using classes instead of inline css

2021-01-09 13:09 UTC, DeKleineKobini commented on torntools/scripts/content/forums/ttForums.js
> +		document.find(".title.title-black.t-hide").insertAdjacentElement("afterEnd", ttBugWarning);
I wouldn't add the t-hide class, as it isn't really relevant to the check imo

2021-01-10 05:47 UTC, Sashank999 commented
Added the changes said @DeKleineKobini .

2021-01-10 08:08 UTC, merged