Trade chat post timer
Mephiles/torntools_extension pull request #441
Opened 2021-03-18 07:09 UTC by Sashank999

This PR also contains some changes to `addPeopleBoxFilter()`.

2021-03-18 15:51 UTC, DeKleineKobini requested changes
Changelog

2021-03-18 15:51 UTC, DeKleineKobini commented on torntools/scripts/content/global/ttGlobal.css
> +	margin-top: 0px;
0

2021-03-18 15:51 UTC, DeKleineKobini commented on torntools/scripts/content/global/ttGlobal.css
> +    padding: 2px 2px 0px 2px;
0

2021-03-18 15:51 UTC, DeKleineKobini commented on torntools/scripts/content/global/ttGlobal.js
> +	if (doc.findAll("div[class*='chat-box-people_SPbEh'] .tt-chat-filter").length === 0) {
Why would you use `*=` and still use the full class? Either do `.class_xxx` or `[class*='class_']`.

2021-03-18 15:51 UTC, DeKleineKobini commented on torntools/scripts/content/global/ttGlobal.js
> +		let peopleBox = document.find("div[class*='chat-box-people_SPbEh']");
same as above

2021-03-19 14:18 UTC, Sashank999 commented
Resolved them all.

2021-03-19 14:48 UTC, DeKleineKobini requested changes
Still missing changelog.
-- Not tested after changes yet.

2021-03-19 14:53 UTC, Sashank999 commented
Changelog added.

2021-03-19 20:04 UTC, merged